name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
        php-versions: [ '8.0', '8.1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --no-check-publish --ansi

      - name: Install dependencies
        run: composer install

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --ansi

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze --memory-limit=-1 --ansi

      - name: Run PHPUnit
        run: vendor/bin/phpunit --colors=always --coverage-text

      - name: Run PHP MD
        run: vendor/bin/phpmd src text ruleset.xml --suffixes php
